apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
      - name: hello-world
        env:
        - name: ENVIRONMENT
          value: e2e
