apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
      - name: hello-world
        image: gcr.io/cybage-devops/spring-boot-hello-world:$BUILD_NUMBER
        env:
        - name: ENVIRONMENT
          value: e2e
