apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: helloworld
  newName: gcr.io/cybage-devops/spring-boot-hello-world
  newTag: $BUILD_NUMBER
